markdown: rdiscount
permalink: /:title/
url: http://nikotung.github.io
name: NikoTung
author: NikoTung
qq: 
email: Nizh2008@gmail.com
duoshuo: NikoTung
beian: 
cnzz: 
weibo: 1864516430
github: NikoTung
pygments: true
safe: true
paginate: 20
about: "这是我的个人博客，好没有什么好东西那得出来介绍"