# Site settings
site: Niko
title: Niko's blog
keywords: blog
description: >-
  Thoughts and other
lang: en-US
timezone:  Asia/HongKong
#google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-42600147-1 # Put your Google Analytics code
#discus-identifier:  XXX

# Author settings
author:
  name: Niko
  bio: Software Engineer <br> Fitness <br> minimalism
  picture: assets/images/profile.jpg 
  github: nikotung # github username
  twitter: nikotung # twitter username
  email: n@eiko.me # email adress


# URL settings
url: "https//blog.eiko.me" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false